package nl.springbank.bean;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.persistence.*;
import java.util.Set;

/**
 * Description
 *
 * @author Tristan de Boer).
 */
@Entity
@Table(name = "bank_account", uniqueConstraints = {@UniqueConstraint(columnNames = "account_id")})
@JsonInclude(JsonInclude.Include.NON_NULL)
public class BankAccountBean {
     /*
        Private methods
     */

    // Autogenerated id (unique for each bank_account in the db)
    @Id
    @Column(name = "account_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long bankAccountId;

    // The balance on the account
    @Column(name = "balance")
    private double balance;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "holder_user_id", nullable = false, insertable = false, updatable = false)
    @JsonBackReference
    @JsonProperty("holder")
    private UserBean user;

    @Column(name = "holder_user_id")
    @JsonProperty("userId")
    private Long userId;

    /*
        Public methods
     */

    public BankAccountBean() {
    }

    public Long getBankAccountId() {
        return bankAccountId;
    }

    public void setBankAccountId(Long bankAccountId) {
        this.bankAccountId = bankAccountId;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }


    @Override
    public String toString() {
        return "BankAccountBean{" +
                "bankAccountId=" + bankAccountId +
                ", balance=" + balance +
                ", user=" + user +
                '}';
    }

    public UserBean getUser() {
        return user;
    }

    public void setUser(UserBean userBean) {
        this.user = userBean;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
}
