package nl.springbank.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.validation.constraints.NotNull;

/**
 * Connection between a bank account and a User.
 *
 * @author Tristan de Boer.
 */
public class UserIbanBean {
    /*
        Private methods
     */

    // Autogenerated id (unique for each relationship in the database)
    @JsonIgnore
    private long id;


    // The userId
    @NotNull
    private long userId;

    @NotNull
    private String iban;

    /*
        Public methods
     */

    public UserIbanBean() {
    }

    public UserIbanBean(long userId, String iban) {
        this.userId = userId;
        this.iban = iban;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public String getIban() {
        return iban;
    }

    public void setIban(String iban) {
        this.iban = iban;
    }

    @Override
    public String toString() {
        return "UserBankAccountBean{" +
                "id=" + id +
                ", userId=" + userId +
                ", iban=" + iban +
                '}';
    }
}
