package nl.springbank.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Connection between a bank account and a User.
 *
 * @author Tristan de Boer.
 */
@Entity
@Table(name = "user_bank_account")
public class UserBankAccountBean {
    /*
        Private methods
     */

    // Autogenerated id (unique for each relationship in the database)
    @Id
    @JsonIgnore
    @Column(name = "user_bank_account_id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;


    // The userId
    @NotNull
    @Column(name = "user_id")
    private long userId;

    @NotNull
    @Column(name = "bank_account_id")
    private long bankAccountId;

    /*
        Public methods
     */

    public UserBankAccountBean() {
    }

    public UserBankAccountBean(long userId, long bankAccountId) {
        this.userId = userId;
        this.bankAccountId = bankAccountId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getBankAccountId() {
        return bankAccountId;
    }

    public void setBankAccountId(long bankAccountId) {
        this.bankAccountId = bankAccountId;
    }

    @Override
    public String toString() {
        return "UserBankAccountBean{" +
                "id=" + id +
                ", userId=" + userId +
                ", bankAccountId=" + bankAccountId +
                '}';
    }
}
